services:
  web-pos:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # React app
      - "8000:8000" # JSON server
    environment:
      - NODE_ENV=development
